builds:
  - binary: ooni-collector
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: "-s -w -X info.Version={{.Version}} -X info.CommitHash={{.Commit}} -X info.BuildDate={{.Date}}"
