builds:
  - binary: ooni-collector
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
