# This is an example config file for ooni-collector
[core]
log-level = "INFO"
is-dev = false

[api]
port = 8080
address = "127.0.0.1"
admin-password = "changeme"
fqn = "unknown"

[db]
url = "mongodb://localhost:32769"

[aws]
access-key-id = ""
secret-access-key = ""
s3-bucket = "ooni-collector"
s3-prefix = "reports"
