# This is an example config file for ooni-collector
[core]
log-level = "INFO"
data-root = "/var/ooni-collector"
is-dev = false

[api]
port = 8080
address = "127.0.0.1"
admin-password = "changeme"

[aws]
access-key-id = "XXX"
secret-access-key = "XXX"
